### ISSUE TITLE
Buyexport

### ISSUE THREAD

**Issue by Brudolfer** [alexander-pick/MKMTool#16]
Hey There, 

i had an issue after exporting my "Buys to Excel"

after hitting the Button excel opened smooth and created the list, but i think there went something wrong :-D

![Unbenannt2](https://user-images.githubusercontent.com/53081928/61529212-1d13f280-aa21-11e9-8071-da89fcc682d0.png)

thanks in advance for your help!

**Comment by tomasjanak** [comment]
Hi, 

do you mean the weird symbols in some of the card names? It is outputting the name in the language of the card, so for Asian & Russian language cards there are sure to be all kinds of problems with character sets. Not sure anybody has the time and interest to make sure it works fine. The most I would be willing to fix about this is to make it write English names.

If you mean the weird numbers in the last column, that is just excel trying to interpret the values as dates, because it sees numbers separated by '.'. Since you are on German locale, the decimal separator is ',', not '.', so it does not see it as numbers because according to your locale, numbers don't have '.' in them. You can either change your system locale to use '.' as decimal separator (probably an overkill) or select the whole column and replace (CTRL+H) all '.' with ',', then I think it will automatically start treating it as numbers (if not, select the whole column -> right click -> cell format -> select Number). 

I'm not sure that this is something we will ever change in MKMTool - MKM is sending all numbers with '.' as separators, so outputting something like this is easy. To change it to the locale of the user (you), we would have to parse everything that is a number and re-format it before writing it out. It can be done, but then it also means that any "import" feature would have to change it back to '.'.
