### ISSUE TITLE
Setting the reference country

### ISSUE THREAD

**Issue by Stefouch** [alexander-pick/MKMTool#19]
Hello!

How could I change the reference country for the Update Price module?

I live in a small country and I wish to not use "domestic" prices and not select "worldwide", but instead I wish to use another neighboring country (e.g. Germany).

**Comment by tomasjanak** [comment]
Hello, 

if you are building MKMTool from source code yourself, you can easily "hack" it by replacing line 135 in the file `MainView.cs` with the country code you want to use, it's "D" for Germany, other countries should follow the codes from this standard: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
So you would replace this:

`                MKMHelpers.sMyOwnCountry = doc2["response"]["account"]["country"].InnerText;`

by this:

`                MKMHelpers.sMyOwnCountry = "D";`

If you are using the binary MKMTool from the zip file on the front page...there is no direct way, someone would have to implement it. 

A possible workaround is in the price update settings - the "Allow worldwide search for low-stock items" checkbox. It will make it so that if there are not enough items found in your country, the search is done again, this time for any country. But in this search, ALL the countries are taken into account, so it usually ends up with the lowest possible prices (mostly thanks to Italian sellers), so it's not exactly the same as pretending you're German, but maybe it's good enough? You can kind of offset the lower prices by moving the "Price based on average - worldwide" slider higher.

**Comment by tomasjanak** [comment]
Faking domestic country is now possible using the [settings](https://github.com/alexander-pick/MKMTool#settings) in config.xml, available in version 0.8.0.0 or newer (commit https://github.com/alexander-pick/MKMTool/commit/8f23f6025e08e8ac645f385116c954eee304c7f1)
