### ISSUE TITLE
Minprice when updating

### ISSUE THREAD

**Issue by mbuttin** [alexander-pick/MKMTool#21]
Hi,

Is it possible to set a minimum price when "updating" ?
I want to stop those 0.06€ order :)

Thanks

**Comment by tomasjanak** [comment]
Hi, 

yes, there is a dedicated settings for that for Rares (and it also works on Mythics) in the "Settings" window. You can also define all kinds of minimum price limits in the myStock.csv file, see the reply ere: https://github.com/alexander-pick/MKMTool/issues/17#issuecomment-524791740 and complete documentation here: https://github.com/alexander-pick/MKMTool#Price-Update (both approaches are described there)

**Comment by mbuttin** [comment]
And when pricing an external list ? It looks like it didn't use the myStock.csv configuration.
Or at least, I can save the pricing on a csv, then modify it by hand, but how to Upload to Mkm a modified csv file ?
Thanks :)

**Comment by tomasjanak** [comment]
That's true, myStock is not used with external lists since it assumes that the cards are not from your stock...didn't think about that. I suppose I could make it check if there is a "MinPrice" column in the list and if so, use the price there as the minimal price for that card (so you could then just add the column, fill it with either special prices for each card or just with a single number for the entire column). Maybe later.

You can modify the price column in the exported list (after pricing), and then use the "Import CSV file..." again, this time importing the updated list, don't do any appraisal and just directly hit the "Upload to MKM" button. What price is uploaded is chosen just above the button, so when modifying the file, modify the column that you will choose there. So if you are using the "MKMTool prices", there should be a column "MKMTool price" in the exported list, modify the values of that column, then choose "MKMTool price" as the "Upload Price" in the Export To MKM section and it will use the modified prices.

**Comment by tomasjanak** [comment]
I have added a checkbox "use myStock.csv" to the module, which does exactly what it sounds like. Also, if the csv list you are pricing itself contains a MinPrice column, it will use it the same way as the ones from myStock (both approaches can be combined).
Added in commit d6a4324facb993609d9e16e07c53739cb496ebad (executable for windows available here: https://tomasjanak.github.io/MKMTool0.7.0.4.zip)
