### ISSUE TITLE
Download Buys to Excel Duplicated Lines

### ISSUE THREAD

**Issue by KonradHoeffner** [alexander-pick/MKMTool#29]
The export result is duplicated dozens of times with different ids and different dates, resulting in a more than 7 MB file with more than 80000 lines.

**Excerpt**

-- | -- | -- | -- | -- | --
-- | -- | -- | -- | -- | --
397407968 | 13.09.10 19:01 | Curse of the Cabal | Time Spiral | English | 0.19
397407968 | 13.09.10 19:01 | Plague Sliver | Time Spiral | English | 0.19
397407968 | 13.09.10 19:01 | Die KÃ¶nigin anflehen | Schattenmoor | German | 0.44
397407968 | 13.09.10 19:01 | Corrupt | Magic 2011 | English | 0.06
397407968 | 13.09.10 19:01 | Elixir of Immortality | Magic 2011 | English | 0.19
397407968 | 13.09.10 19:01 | Korlash, Heir to Blackblade | Future Sight | English | 1.94
299566488 | 13.09.10 19:01 | Curse of the Cabal | Time Spiral | English | 0.19
299566488 | 13.09.10 19:01 | Plague Sliver | Time Spiral | English | 0.19
299566488 | 13.09.10 19:01 | Die KÃ¶nigin anflehen | Schattenmoor | German | 0.44
299566488 | 13.09.10 19:01 | Corrupt | Magic 2011 | English | 0.06
299566488 | 13.09.10 19:01 | Elixir of Immortality | Magic 2011 | English | 0.19
299566488 | 13.09.10 19:01 | Korlash, Heir to Blackblade | Future Sight | English | 1.94

**Comment by KonradHoeffner** [comment]
Also the language differs, is it possible to have all in English?

**Comment by tomasjanak** [comment]
I've fixed the bug with the duplication (commit https://github.com/alexander-pick/MKMTool/commit/572fe22273c235a59a25a389a8ec93bcb4658266 ), thanks for reporting this. It seems correct now, but let me know if you find some mistake.

I don't like making changes to how a module behaves (like changing the language of the output) so that people who are already using it are not surprised/annoyed. But given that this clearly wasn't really working correctly so far anyway, I've made the change (commit https://github.com/alexander-pick/MKMTool/commit/c8e0ee49a8161cceff6a44f52ae250896b57262e). But if somebody wants to add some settings to toggle between "export in english" / "export in original language", it would be nice (I'm not going to do that though).

The link to the windows binary compiled by me is updated ([version 0.7.0.5](https://tomasjanak.github.io/MKMTool0.7.0.5.zip)).

Note: the translation works only for magic singles, any other product will be the way MKM sends it. I can verify that for M:tG booster boxes MKM is always using English names even for boxes in other languages (while for singles they use the language of the card). But there might be products that will end up non-english, particularly singles of different games than M:tG.
