### ISSUE TITLE
Setting prices by other commercial sellers

### ISSUE THREAD

**Issue by MartinLKoenig** [alexander-pick/MKMTool#41]
Thanks for this amazing tool. Saves a lot of time.

Is a price estimation possible, that includes (only) commercial sellers/powersellers?

I figured since it is a clickable checkbox when viewing article pages and can be included in filters, it could be possible. 

Regards

**Comment by tomasjanak** [comment]
It is possible, but currently not implemented in MKMTool.

**Comment by MartinLKoenig** [comment]
Is an implementation like that planned or are there some edits one with minor knowledge about the programming could add to work this out? 
Would be much appreciated. 

regards

**Comment by tomasjanak** [comment]
Somebody would have to pay me to do that.

Luckily for you, somebody just did, so this feature should be coming soon.

**Comment by MartinLKoenig** [comment]
Is there an ETA or an other place where one could follow the progress? This is really interesting to me.

**Comment by tomasjanak** [comment]
Hi, I have pushed the updates to a separate branch 0.8_candidate (https://github.com/alexander-pick/MKMTool/tree/0.8_candidate) since there are still some issues, some of the code might have to be reverted. However, the filtering based on seller type is there and should work correctly.  Link to binaries is in the usual place on that branch (https://github.com/alexander-pick/MKMTool/tree/0.8_candidate#installation-and-starting-off).

**Comment by tomasjanak** [comment]
Added in commit https://github.com/alexander-pick/MKMTool/commit/c1a824020752ea00baeb616ac472059c679f128b (available in version 0.8.0.0 or newer)
