### ISSUE TITLE
config.xml

### ISSUE THREAD

**Issue by Aaages03** [alexander-pick/MKMTool#52]
Hey Guys, 

how can i get my API Tokens from MKM?

I tried to work with this Tool, but can´t get started. 
The Tutorial and the "how to start off" is not clearly written. 

I can not get any further without my Tokens i think. 

Can anybody help me?

Regards, 
Aaages

**Comment by tomasjanak** [comment]
On the cardmarket website, click Account -> API Settings and generate tokens for "Dedicated App" (you can put anything you want as the app name). You need an account which is able to sell to use most of the seller functions. Once you generate it, four random strings of letters and numbers will appear there: appToken, appSecret, accessToken and accessSecret. Copy-paste those strings inside config.xml instead of the ENTER_YOUR_xxxx_INSTEAD_OF_THIS_TEXT, where xxxx are the names of the values.

**Comment by Aaages03** [comment]
I tried that actually, but nothing happens, when i try to create these tokens. 
Are these tokens available for private users?

**Comment by tomasjanak** [comment]
> 
> 
> Are these tokens available for private users?

Yes, but I think you have to be a seller already. I don't remember anymore, but I think there is some delay before you get the tokens for the first time, like one day or so. Doesn't the API settings page say something like that?

**Comment by Aaages03** [comment]
I´m registered since 2019. I also purchased some stuff and sold some stuff. 
My API-Settings are looking like in the picture. When i click on "send" nothing happens.

![API Settings](https://user-images.githubusercontent.com/78268182/106361276-5c611600-631d-11eb-8240-9ce2c2ab6bdb.PNG)

**Comment by tomasjanak** [comment]
If you clicked Absenden and nothing is happening, I think you just need to wait. If they don't appear by Monday, you will probably need to contact support.

**Comment by Aaages03** [comment]
Alright. 
Thank u for ur help!

**Comment by tomasjanak** [comment]
I assume it has worked, reopen and add info if not.
